---
title: "Виды анализа и R Markdown"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

> Способность к анализу не следует смешивать с простой изобретательностью, ибо аналитик всегда изобретателен, тогда как не всякий изобретательный человек способен к анализу.

*Эдгар Аллан По, Убийство на улице Морг*

# Введение

Цель данной работы - привести **примеры научных работ**, в которых использовались конкретные **виды анализа** и обосновать корректность подобранных примеров. Виды анализа для моего варианта:

1. *Дедуктивный (Логический)*
2. *Механистический*

Также необходимо продемонстрировать умение пользоваться языком разметки **R Markdown**. Для этого данная работа должна быть создана с его помощью и содержать следующие элементы:

- *заголовки разных уровней*
- *маркированные списки*
- *нумерованные списки*
- *URL-ссылки*
- *математические формулы в формате LaTeX*
- *изображения*
- *цитаты*
- *таблицы*

Пойдем по порядку.

# Виды анализа

виды балин

## Дедуктивный анализ

### Описание

Данный вид анализа подразумевает **экстраполяцию выводов** о малой выборке на всю совокупность.
Особенности дедуктивного анализа:

- *Позволяет оценить значение переменной для генеральной совокупности и указывает меру неопределенности полученной оценки*
- *Тосность выводов сильно зависит схемы выборки (выборка должна быть репрезентативна)*

### Пример

## Механистический анализ

### Описание

Выявление **точной зависимости** одних величин от других выделяет механистический анализ среди прочих видов анализа.
Особенности механистического анализа:

- *Данному виду анализа хорошо подходит термин "моделирование"*
- *Применяется к ситуациям, которые хорошо моделируются детерменированными уравнениями*
- *Обычно примениется к физическим и инженерным наукам (где скрытые зависимости мало влияют на объекты)*
- *Часто единственный шум в данных - ошибки измерения*

### Пример

# Заключение

В ходе работы были подобраны и обоснованы примеры для интересующих видов анализа, а также с помощью RMarkDawn был создан этот документ с внедрением необходимых структурных элементов.

[Репозиторий проекта на GitHub.](https://github.com/Erik-s45/RMarkdawn)
